### PR TITLE
Added: Support for Armenian Language

### PR DESCRIPTION
**Pull request by hovikman**
Add the following categories for Armenian:
- Address
- Color
- Commerce
- Company
- Industry
- Internet
- Name
- Phone

### CODE REVIEW

**Comment by anthonator** [comment]
What format are we using for the module specific country codes? It looks like the existing examples use 2 letter country codes? Should this change from `Arm` to `Am`?

**Comment by vbrazo** [comment]
@anthonator that's a good point. I believe we should use 2 letter country codes in the format. Check [this reference](https://wiki.openstreetmap.org/wiki/Nominatim/Country_Codes) out to see the `ISO 3166-1` column.

**Comment by anthonator** [comment]
Also make sure to change the file names to match the module names.

**Comment by anthonator** [comment]
@vbrazo are you good to merge this with @hovikman's latest commits?

**Comment by vbrazo** [comment]
looks good 👍

**Comment by igas** [comment]
Hi @hovikman, this is a good idea. Generally, my thoughts were to use the first part as a language code and second as a locale. For example `EnUs`, `EnAu` - language is English and names would be the same, but addresses not. So if we specify locale to `EnAu` it'll look into:

```
Faker.Name.EnAu.name
Faker.Name.En.name
Faker.Name.name
```

**Comment by hovikman** [comment]
Hi @igas, thank you for your feedback. I'll go ahead and change the locale to 'hy'.

**Pull request merged**
