### PR TITLE
Fix Elixir 1.17 warnings

### LINKED ISSUE #558: Compile warnings with Elixir 1.17 rc
Seeing warnings like this.

```
warning: using map.field notation (without parentheses) to invoke function Faker.Random.Elixir.random_uniform() is deprecated, you must add parentheses instead: remote.function()
Warning:   (faker 0.18.0) lib/faker.ex:109: Faker.random_uniform/0
  (faker 0.18.0) lib/faker/address.ex:188: Faker.Address.latitude/0
```

I can't say I quite understand the issue from taking a peak at the current code and the release notes.
https://github.com/elixir-lang/elixir/releases/tag/v1.17.0-rc.0

### PR DESCRIPTION
**Pull request by ypconstante**
This fixes some of the warnings being logged when using Elixir 1.17
- Fix compilation warnings caused by single quote usages. In some places I changed to double quotes, in others to `~c` 
- Fix runtime warning on Faker.random_uniform/0 caused by missing parenthesis in function call

There are still some warnings because of pattern matching on ranges, but fixing this requires an API change or bumping the minimum Elixir version to 1.12 to be able to match or ignore the range step.

Closes https://github.com/elixirs/faker/issues/558

I've added:

- [ ] USAGE.md docs if applicable
- [X] CHANGELOG.md

### CODE REVIEW

**Comment by igas** [comment]
Nice one, before we proceed with this one, can you please add CI for elixir 17 as a separate PR. Cheers.

**Comment by ypconstante** [comment]
Some tests are breaking with Elixir 1.16 and Elixir 1.17, similar to the issue blocking tests with OTP 26

**Comment by igas** [comment]
@ypconstante it would be good to see it before fixing, as main is green.

**Comment by ypconstante** [comment]
Done https://github.com/elixirs/faker/pull/562

**Comment by igas** [comment]
Thank you @ypconstante!

**Comment by seantanly** [comment]
@ypconstante thank you for the fixes!

@igas would it be possible to cut a release with the elixir 1.17 warning fixes? I would prefer to rely on the official hex package than pointing here on the github repo. Thank you in advance! 🙏

**Comment by dkarter** [comment]
@igas / @anthonator (👋🏼) just checking in on this, would you be able to cut a new release that contains this fix please? 🙏🏼

**Comment by odarriba** [comment]
It would be awesome if a new release could be done to reduce the amount of warnings generated at compile time 🙏 

Thanks!!

**Pull request merged**
