### PR TITLE
Introduce Faker.Iban.iban

### PR DESCRIPTION
**Pull request by tobyhinloopen**
Generating pretty IBAN numbers with valid checksum, country codes & length

```elixir
Faker.Iban.iban #=> "IT34K5534420705QL3FT3SE7OTG"
Faker.Iban.iban "NL" #=> "NL90FWAC8717013067"
Faker.Iban.iban ["NL", "BE"] #=> "BE22587804301223"
Faker.Iban.iban "NL", ["ABNA"] #=> "NL39ABNA4314302905"
```

### CODE REVIEW

**Comment by tobyhinloopen** [comment]
Renamed module `Faker.Iban` to `Faker.Bank` to make it more similar to Ruby's Faker: https://github.com/stympy/faker/blob/master/doc/bank.md

**Comment by igas** [comment]
what do you think about add it to `Faker.Code`?

**Comment by tobyhinloopen** [comment]
Moved `iban/#` to `Faker.Code.Iban` and added delegates to `Faker.Code.Iban.iban/#` in `Faker.Code`. I personally preferred the `Faker.Code.Iban` module to be seperate because it includes relatively much private functions that are used for iban only.

I personally still prefer `Faker.Bank.iban/#` though, since Ruby's Faker has the same method.

**Comment by igas** [comment]
@tobyhinloopen I can understand preference to match ruby one, but on the other hand it's not always make sense I think + I don't want to always be follower, I have some ideas that we can do that ruby one doesn't have.

**Pull request merged**
