### PR TITLE
Fix compilation warnings

### PR DESCRIPTION
**Pull request by belaustegui**
As stated in issue #52 , when compiling Faker with Erlang 19.0 I'm getting some warnings about deprecated modules and functions:

<details>
```
==> faker
Compiling 22 files (.ex)
warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
  lib/faker/bitcoin.ex:13

warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1
  lib/faker/bitcoin.ex:17

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/avatar.ex:43

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/avatar.ex:48

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/code.ex:5

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/code.ex:11

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/code.ex:17

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/internet.ex:31

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/internet.ex:61

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/address.ex:60

warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/address.ex:61

warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/address.ex:69

warning: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
  lib/faker/address.ex:70

Generated faker app
```
</details>

This pull request fixes those deprecation warnings by using the `:rand`[1] module instead the old `:random`[2] and by updating the call to `crypto:rand_bytes/1` to `crypto:strong_rand_bytes/1`[3].

[1] http://erlang.org/doc/man/rand.html
[2] http://erlang.org/doc/man/random.html
[3] http://erlang.org/doc/man/crypto.html#strong_rand_bytes-1

### CODE REVIEW

**Comment by belaustegui** [comment]
I've also updated the Travis CI configuration to run the tests on Erlang 19.0 version.

**Comment by belaustegui** [comment]
Looks like Elixir 1.0.5 does not like the changes so far... :(

**Comment by igas** [comment]
If we'll update to `rand` we'll drop OTP 17 support. But I think it's time to do that. Thanks for the contribution!
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by belaustegui** [comment]
Wonderful! Thank you!! :raised_hands:

**Comment by nathany** [comment]
Looking forward to the next release -- with this.

**Comment by belaustegui** [comment]
Thank you very much! :heart:

**Comment by igas** [comment]
I'll release it soon, I'll also rewrite some parts, ETA Tue next week, will work on it on http://elixir.camp/

**Comment by igas** [comment]
Thanks, everyone, it's published, please test it and I'll be happy to hear any feedback.

**Pull request merged**
