### PR TITLE
Faker.Food.PtBr

### PR DESCRIPTION
**Pull request by vbrazo**
I've added:

- [x] CHANGELOG.md
- [x] Add `Faker.Food.PtBr`
- [x] Fix `Faker.StarWars` doctests

### CODE REVIEW

**Comment by igas** [comment]
Hi @vbrazo,

It looks good to me, I'm planning to release bug fix release first and will merge it when we'll be doing next minor release.

**Comment by vbrazo** [comment]
@igas sounds good 🚀

**Comment by anthonator** [comment]
Any reason this never got merged?

**Comment by vbrazo** [comment]
@anthonator no. We were actually just waiting for `0.13.0`and it looks like we have a good amount of PRs to release a new version.

**Pull request merged**
